version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty2007
      MYSQL_DATABASE: my_blog_development
    volumes:
      - db_data:/opt/homebrew/var/mysql/
    ports:
      - "3306:3306"

  web:
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3500 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3500:3500"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:qwerty2007@db:3306/my_blog_development

volumes:
  db_data: